### ISSUE TITLE
Update - timeline_page Component

### ISSUE THREAD

**Issue by alyhxn** [dat-ecosystem/website#23]
## `todo`

- [x] Update timeline_page_v0.1.0
   - `@input` :package: [`app_timeline_v0.1.1`](https://github.com/dat-ecosystem/dat-ecosystem/blob/main/src/node_modules/app-timeline/app-timeline.js) from #22 
   - `@input` :package: [`app_footer_v0.1.1`](https://github.com/dat-ecosystem/dat-ecosystem/blob/main/src/node_modules/app-footer/app-footer.js) from #11 
   - [x] update the timeline_page component
   - `@output` :package: [`timeline_page_v0.1.1`](https://github.com/dat-ecosystem/dat-ecosystem/blob/main/src/node_modules/timeline-page/timeline-page.js) from [comment](https://github.com/dat-ecosystem/dat-ecosystem/issues/23#issuecomment-1914598731)

---

- [ ] Finalize timeline_page_v0.1.?
   - [ ] code timeline_page
   - `@output` :package: `timeline_page_v0.1.?` from `comment`

**Comment by alyhxn** [comment]
### tasks - `2024.01.28`

- Update timeline_page_v0.1.0
   - update the timeline_page component
   - `@output` :package: [`timeline_page_v0.1.1`](https://github.com/dat-ecosystem/dat-ecosystem/blob/main/src/node_modules/timeline-page/timeline-page.js)

---

### worklog

---

### feedback
Initialized the issue

---

### proposals
